FROM debian:stable-slim

RUN mkdir -p /root/.config/fish

# install apps and libs
RUN echo 'deb http://deb.debian.org/debian sid main' >>/etc/apt/sources.list
RUN apt-get update && apt-get install -y inetutils-ping coreutils libc6 xsel gpg wget tmux vim unzip git git-lfs fzf curl wget silversearcher-ag make ruby jq sudo

# install latest fish
RUN echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/4/Debian_Unstable/ /' | tee /etc/apt/sources.list.d/shells:fish:release:4.list
RUN curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:4/Debian_Unstable/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg >/dev/null
RUN apt update -y
RUN apt autoremove -y
RUN apt install -y fish

# install task
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

# fnm
RUN curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "/root/.fnm" --skip-shell
ENV PATH="/root/.fnm:$PATH"
RUN echo 'eval "$(fnm env --use-on-cd --shell fish)"' >>~/.config/fish/config.fish
# node
RUN fnm install 22 --resolve-engines --corepack-enabled
RUN fnm default 22
# pnpm
RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL=$(which fish) sh -

RUN curl https://raw.githubusercontent.com/d-mv/dotfiles/refs/heads/local/tmux/tmux.conf >>~/.tmux.conf
RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
RUN echo "set -g @plugin 'tmux-plugins/tpm'" >>~/.tmux.conf
RUN echo "set -g @plugin 'tmux-plugins/tmux-sensible'" >>~/.tmux.conf
RUN echo "set -g @plugin 'arcticicestudio/nord-tmux'" >>~/.tmux.conf
RUN echo "run '~/.tmux/plugins/tpm/tpm'" >>~/.tmux.conf

RUN curl https://raw.githubusercontent.com/d-mv/dotfiles/refs/heads/local/git/gitconfig >>~/.gitconfig

RUN git clone https://github.com/d-mv/dotfiles.git ~/.dotfiles

RUN chsh -s $(which fish) $USER

# configure fish
RUN curl clone https://raw.githubusercontent.com/d-mv/dotfiles/refs/heads/local/config.fish >>~/.config/fish/config.fish
RUN curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
RUN fish -c "fisher install jorgebucaran/hydro"

ENV DEV_ENV=true
RUN echo "Welcome to the dev environment!"

ENTRYPOINT ["fish"]
